### PR TITLE
2.20.3 release, 2.19.5 release, and daily website updates for future posts

### PR DESCRIPTION
**Pull request by jodygarnett**

### CODE REVIEW

**Comment by jodygarnett** [comment]
@ianturton I have added the 2.19.5 release to this pull request along with the same security considerations as the 2.20.3 release.

**Comment by jodygarnett** [comment]
Added a workflow change to perform daily website updates; this should allow the PR to be merged today; and have blog posts show up automatically next Tuesday at 12:30 am.

**Review by ianturton — APPROVED** [review]

**Comment by jodygarnett** [comment]
Okay, merged, we will see if it is auto published on Tuesday.

**Comment by jodygarnett** [comment]
Well that almost worked; the posts are not up yet ...  but the landing page lists 2.20.3 and 2.19.5:

image

I guess it really needs to check if the release is published yet; or process and sort and grab the latest for the series.

**Pull request merged**
