### PR TITLE
Add "meggsimum" as service provider

### PR DESCRIPTION
**Pull request by JakobMiksch**
This PR adds the company meggsimum as "Additional Service Provider" to the [support page](http://geoserver.org/support/) of the GeoServer homepage.

An additional message to the mailing list geoserver-users@lists.sourceforge.net has been sent. Here to copy of it:

> Dear GeoServer-list,
> 
> we, the company meggsimum (https://meggsimum.de/), have been working
> with GeoServer for many years and offer commercial support for it.
> 
> Could we be listed as "Additional Service Provider"
> (http://geoserver.org/support/) on the support web page?
> 
> We already prepared a Pull Request with our description and logo:
> https://github.com/geoserver/geoserver.github.io/pull/114
> 
> Please let us know if there is anything else required for being part of
> the list.
> 
> Thanks and kind regards,
> Jakob

### CODE REVIEW

**Comment by jodygarnett** [comment]
Please ask on the email list! And thanks for helping folks with GeoServer

**Comment by jodygarnett** [comment]
PR looks good, just ask on the email list and we can merge this

**Comment by JakobMiksch** [comment]
Thank @jodygarnett for the review.
I already sent an email to "geoserver-user" list: https://sourceforge.net/p/geoserver/mailman/message/37413188/
Or would "geoserver-devel" be the right list for that, or another list?

**Comment by jodygarnett** [comment]
geoserver-devel is the correct list, most developers only read the user
list when they are waiting for a build to compile :)
--
Jody Garnett

**Review by jodygarnett — APPROVED** [review]

**Comment by JakobMiksch** [comment]
@jodygarnett thanks for merging
I added minor follow-up PR regarding the formatting https://github.com/geoserver/geoserver.github.io/pull/116

**Pull request merged**
