### PR TITLE
GeoServer 2.19 release with page generation

### PR DESCRIPTION
**Pull request by jodygarnett**
Little did we know updating the GWC `release.rb` would unleash ...

A custom `_plugin/release.rb`:

- generate release pages from the announcement blog posts
- generates the `stable`, `maintain` and `dev` pages by checking if the `_config.yml` match a release anouncement
- generates the nightly pages from from `_config.yml` version, branch and jira information
- fills in a placeholder `dev` page based (if match was not found in a release announcement)

I also found:

- a few broken links to 2.16.x series announcements (they were not in the acouncement category)
- at least one missing image (which I was able to find on blog.geoserver.org)

Also this include the 2.19.1 release scheduled for monday so to test use:
```
bundle exec jekyll serve --future --watch 
```

I left some standard error messages just so I can confirm it is doing something:
```
"release page generator ..."
"Generating release/2.16-RC release_216 page"
"Generating release/2.16.0 release_216 page"
"Generating release/2.16.1 release_216 page"
"Generating release/2.16.2 release_216 page"
"Generating release/2.17-RC release_217 page"
"Generating release/2.17.0 release_217 page"
"Generating release/2.16.3 release_216 page"
"Generating release/2.17.1 release_217 page"
"Generating release/2.16.4 release_216 page"
"Generating release/2.17.2 release_217 page"
"Generating release/2.16.5 release_216 page"
"Generating release/2.18-RC release_218 page"
"Generating release/2.18.0 release_218 page"
"Generating release/2.17.3 release_217 page"
"Generating release/2.18.1 release_218 page"
"Generating release/2.17.4 release_217 page"
"Generating release/2.18.2 release_218 page"
"Generating release/2.17.5 release_217 page"
"Generating release/2.19-RC release_219 page"
"Generating release/2.19.0 release_219 page"
"Generating release/2.18.3 release_218 page"
"Generating release/maintain page"
"Generating release/2.19.1 release_219 page"
"Generating release/stable page"
"Generating release/dev placeholder"
"Generating release/main page"
"Generating release/2.19.x page"
"Generating release/2.18.x page"
```

### CODE REVIEW

**Review by ianturton — APPROVED** [review]

**Comment by jodygarnett** [comment]
Apparently this will not be so easy:
- https://github.com/jekyll/jekyll/issues/5265

**Comment by jodygarnett** [comment]
Okay that worked, a workflow is now being used to publish to `gh-pages` branch.

**Comment by jodygarnett** [comment]
The instructions for https://github.com/jeffreytse/jekyll-deploy-action asked for a bit more permissions than I was comfortable with, see https://github.com/jeffreytse/jekyll-deploy-action/issues/21

**Comment by aaime** [comment]
Hem... looks like lots of action but I'm not understanding. Is the release.rb going to work at runtime or deploy time? Or is it something we have to run locally during a release?

**Comment by jodygarnett** [comment]
It is a plugin I am writing for Jekyll and works at build time as part of Jekyll generating the static pages.

The plugin implements a is a generator:
- Produces the “Page” data structure that Jekyll works from. Indeed is producing the same page data structure that we were creating by hand (sometimes multiple times for `release/stable` and `release/2.19.1`).
- Next I am going to get it to produce a `site.data.releases` data structure which the download page can use

Here is the documentation I have been following https://jekyllrb.com/docs/plugins/generators/

**Pull request merged**
